version: "3.9"

services:
  amm-server:
    container_name: amm-server
    image: siailyadev/amm-server:0.0.5
    ports:
      - "8001:8000"
    volumes:
      - ./server/model:/app/model

  aam-client:
    container_name: aam-client
    image: siailyadev/amm-client:0.0.5
    ports:
      - "3000:80"
